#!/usr/bin/env python3
"""Exercise the Siemens 9772 terminal over its upstream serial port.

Line format (set by the factory firmware):
    9600 baud, 8 data bits, odd parity, 1 stop bit (8O1)

Protocol summary (extracted from firmware disassembly):

    Default state (0x0F):
        STX (0x02)    -> enter text mode (state 0x11)
        DC1 (0x11)    -> next byte = one character written at cursor
        DC3 (0x13)    -> next byte = command (DC3 escape)
        DC4 (0x14)    -> next byte = slave poll; terminal echoes 0x14 + byte

    Text mode (state 0x11, entered by STX):
        ETX (0x03)    -> leave text mode, back to default
        DC3 (0x13)    -> next byte = DC3-escape command (then stay in text mode)
        anything else -> written at cursor, cursor advances. Bytes with
                         bit 7 set are forced to 0x7F (DEL) before display.

    DC3-escape commands (following a DC3 either in default or text mode):
        0x08          -> transmit `0x12 0x20` (status response)
        0x09          -> transmit `0x12 <id>` where <id> is the slave address
                          read from DIP switches: 0x01, 0x02 or 0x04
        0x30-0x57     -> set cursor to BCD column 0..39 within current row
        0x80-0x8F     -> set display bank/row (P2 upper nibble = cmd & 0x0F)
        0xC0          -> fill current bank with 0x00
        0xC1          -> fill current bank with 0x20 (space) -- "clear screen"
        0xC2          -> all banks invisible + fill bank 0 with 0x00
        0xC3          -> transmit `0x12 0x80` (status report)
        0xC4          -> clear current row to 0x00, cursor home
        0xC5          -> clear current row to 0x20, cursor home
        0xC6          -> start attribute-blink mode A (toggle P1.0 each tick)
        0xC7          -> start attribute-blink mode B (toggle P1.1 each tick)
        0xC8          -> stop attribute blink (freeze current state)
        anything else -> reset to default state

    DC4 (0x14) slave-response:
        terminal waits for T0 low (TxRDY), then transmits 0x14 followed
        by the received byte back over the same line. Useful for
        ping/address probing on the RS-422/485 bus.

Underline: the firmware provides NO software control of the
per-character underline. P1.0 and P1.1 are the only P1 bits it
manipulates, and those drive attribute blink (cursor / alt-blink). The
global "underline under every cell" is therefore hardware-generated by
the TTL display controller and is always on.

This script assumes a straight two-wire connection via an RS-422/485
transceiver onto the terminal's DTE upstream port.

Usage:
    python3 exercise.py /dev/ttyUSB0
    python3 exercise.py /dev/ttyUSB0 --demo cycle      # run every demo
    python3 exercise.py /dev/ttyUSB0 --demo clear
    python3 exercise.py /dev/ttyUSB0 --demo chargen    # show whole charset
    python3 exercise.py /dev/ttyUSB0 --demo umlaut
    python3 exercise.py /dev/ttyUSB0 --demo blink
    python3 exercise.py /dev/ttyUSB0 --demo ping       # DC4 probe
"""
from __future__ import annotations

import argparse
import sys
import time

try:
    import serial
except ImportError:
    sys.exit("pyserial is required: pip install pyserial")


# --- Protocol constants --------------------------------------------------

STX = 0x02
ETX = 0x03
BS  = 0x08
TAB = 0x09
DC1 = 0x11
DC2 = 0x12      # response prefix (terminal -> host)
DC3 = 0x13
DC4 = 0x14

# DC3-escape commands (the byte sent after a DC3)
CMD_STATUS_QUERY    = BS    # 0x08: tx 0x12 0x20
CMD_ADDRESS_QUERY   = TAB   # 0x09: tx 0x12 <slave-id>  (0x01/0x02/0x04)
CMD_FILL_NULL       = 0xC0
CMD_CLEAR_SCREEN    = 0xC1  # fill with space (0x20)
CMD_HIDE_ALL        = 0xC2  # bit-7-clear every cell + fill bank 0 with 0x00
CMD_STATUS_REPORT   = 0xC3  # transmits 0x12 0x80
CMD_CLEAR_ROW_NULL  = 0xC4  # clear current row to 0x00, cursor home
CMD_CLEAR_ROW_SPACE = 0xC5  # clear current row to 0x20, cursor home
CMD_BLINK_A_START   = 0xC6  # P1.0 toggling -> cursor blink
CMD_BLINK_B_START   = 0xC7  # P1.1 toggling -> alt blink
CMD_BLINK_STOP      = 0xC8

# Row / column encoding: cursor position is given by a byte in [0x30 .. 0x57].
# The firmware subtracts 0x30 and looks up page-3 BCD table; the result is a
# value 0..39 that drives R1 (display-cell offset within the current row).
def col_byte(col: int) -> int:
    """Encode column 0..39 as the wire byte expected after DC3."""
    if not 0 <= col <= 39:
        raise ValueError(f"column {col} out of range 0..39")
    return 0x30 + col


def row_byte(row: int) -> int:
    """Encode display row/bank as a 0x80..0x8F byte after DC3.

    The firmware sets P2 upper nibble = (byte & 0x0F), so rows map 1:1 to
    0x80..0x8F. The RAM[0x16] limit (set from DIP switches) caps the row
    count at either 2, 6 or 12 banks. Rows beyond that are rejected.
    """
    if not 0 <= row <= 15:
        raise ValueError(f"row {row} out of range 0..15")
    return 0x80 + row


# --- Serial helpers ------------------------------------------------------

class Terminal:
    def __init__(self, port: str, baud: int = 9600):
        # Some UARTs accept PARITY_ODD directly. 8O1 frame: 8 data + parity + 1 stop.
        self.ser = serial.Serial(
            port=port,
            baudrate=baud,
            bytesize=serial.EIGHTBITS,
            parity=serial.PARITY_ODD,
            stopbits=serial.STOPBITS_ONE,
            timeout=0.5,
        )

    def send(self, *bs):
        """Send a sequence of ints/bytes/strs."""
        buf = bytearray()
        for b in bs:
            if isinstance(b, int):
                buf.append(b & 0xFF)
            elif isinstance(b, (bytes, bytearray)):
                buf.extend(b)
            elif isinstance(b, str):
                buf.extend(b.encode("latin-1"))
            else:
                raise TypeError(f"bad arg {type(b)}")
        self.ser.write(bytes(buf))
        self.ser.flush()

    def read(self, n: int, timeout: float | None = None) -> bytes:
        if timeout is not None:
            self.ser.timeout = timeout
        return self.ser.read(n)

    def close(self):
        self.ser.close()

    # Protocol primitives
    def clear_screen(self):
        """Fill the whole display with spaces."""
        self.send(DC3, CMD_CLEAR_SCREEN)

    def fill_null(self):
        """Fill the whole display with 0x00 (all cells invisible)."""
        self.send(DC3, CMD_FILL_NULL)

    def goto(self, row: int, col: int):
        """Move cursor to (row, col) via DC3 escapes. Not inside a text block."""
        self.send(DC3, row_byte(row), DC3, col_byte(col))

    def write_text(self, row: int | None, col: int | None, s: str):
        """Write a string at (row, col). Uses STX ... ETX framing and
        DC3-positioning inside the block. Row/col may be None to skip."""
        self.send(STX)
        if row is not None:
            self.send(DC3, row_byte(row))
        if col is not None:
            self.send(DC3, col_byte(col))
        self.send(s)  # literal bytes; bit 7 is filtered by firmware
        self.send(ETX)

    def write_one(self, ch: int):
        """Display one character at the current cursor (DC1 <char>)."""
        self.send(DC1, ch)

    def blink_a(self):      self.send(DC3, CMD_BLINK_A_START)
    def blink_b(self):      self.send(DC3, CMD_BLINK_B_START)
    def blink_off(self):    self.send(DC3, CMD_BLINK_STOP)

    def status_report(self, timeout: float = 1.0) -> bytes:
        """DC3 0xC3 -> expect `0x12 0x80` back."""
        self.ser.reset_input_buffer()
        self.send(DC3, CMD_STATUS_REPORT)
        return self.read(2, timeout=timeout)

    def status_query(self, timeout: float = 1.0) -> bytes:
        """DC3 0x08 (BS) -> expect `0x12 0x20` back."""
        self.ser.reset_input_buffer()
        self.send(DC3, CMD_STATUS_QUERY)
        return self.read(2, timeout=timeout)

    def address_query(self, timeout: float = 1.0) -> bytes:
        """DC3 0x09 (TAB) -> expect `0x12 <slave-id>` back. <slave-id> is
        0x01, 0x02 or 0x04 depending on the DIP switches read at boot."""
        self.ser.reset_input_buffer()
        self.send(DC3, CMD_ADDRESS_QUERY)
        return self.read(2, timeout=timeout)

    def dc4_ping(self, payload: int = 0x00, timeout: float = 1.0) -> bytes:
        """Slave-poll: terminal echoes 0x14 <payload> back to the host."""
        self.ser.reset_input_buffer()
        self.send(DC4, payload)
        return self.read(2, timeout=timeout)


# --- Demos ---------------------------------------------------------------

def demo_clear(t: Terminal):
    t.clear_screen()


def demo_banner(t: Terminal):
    t.clear_screen()
    time.sleep(0.2)
    t.write_text(0, 0, "SIEMENS 9772 TERMINAL")
    t.write_text(1, 0, "exercise.py running")


def demo_chargen(t: Terminal):
    """Write every printable code from 0x20 to 0x7A across the rows."""
    t.clear_screen()
    time.sleep(0.2)
    # 40 cells per row; put 0x20..0x7A in blocks of 40 starting on row 0.
    codes = list(range(0x20, 0x7B))
    for start in range(0, len(codes), 40):
        row = start // 40
        chunk = bytes(codes[start:start + 40])
        t.send(STX, DC3, row_byte(row), DC3, col_byte(0))
        # 0x03 (ETX) and control chars can confuse the text-mode handler,
        # so send them as one-shots via DC1.
        for b in chunk:
            if b in (ETX, DC1, DC3, DC4):
                t.send(DC1, b)
            else:
                t.send(b)
        t.send(ETX)


def demo_umlaut(t: Terminal):
    """Show the German upper-page glyphs (Ö Ü ^ Ä and ö ü ß ä).

    Writing a char with bit 7 set via STX/DC1 gets filtered to 0x7F by the
    firmware (multi-drop control-byte guard). To reach the upper chargen
    page we have to drive P2.upper via the 0x80-0x8F bank-select escape,
    then put a normal 7-bit char there. (If the hardware maps the upper
    chargen page differently on a given unit, this is the demo to check.)
    """
    t.clear_screen()
    time.sleep(0.2)
    samples = [
        (0x80, "Oe"),
        (0x81, "Ue"),
        (0x82, "^^"),
        (0x83, "Ae"),
        (0xA0, "oe"),
        (0xA1, "ue"),
        (0xA2, "ss"),
        (0xA3, "ae"),
    ]
    for i, (code, label) in enumerate(samples):
        row, col = divmod(i, 4)
        row += 0          # all on row 0/1
        col = col * 8
        t.send(STX)
        t.send(DC3, row_byte(row))
        t.send(DC3, col_byte(col))
        # Select bank for upper chargen page - if the display uses P2.4-P2.7
        # as an extra address line into the chargen, this is how we flip it.
        t.send(DC3, 0x80 + (code >> 4))
        t.send(code & 0x7F)  # masked by firmware
        t.send(ETX)
        # tag each glyph with its ASCII fallback label
        t.write_text(row, col + 2, label)
        time.sleep(0.2)


def demo_positions(t: Terminal):
    """Walk one character across all 40 columns, twice."""
    t.clear_screen()
    for col in range(40):
        t.write_text(0, col, "*")
        time.sleep(0.05)
    for col in range(40):
        t.write_text(0, col, " ")
        time.sleep(0.05)


def demo_blink(t: Terminal):
    """Enter blink mode A for 3s, mode B for 3s, then stop."""
    t.clear_screen()
    t.write_text(0, 0, "BLINK A (P1.0 toggle)")
    t.blink_a()
    time.sleep(3.0)
    t.write_text(1, 0, "BLINK B (P1.1 toggle)")
    t.blink_b()
    time.sleep(3.0)
    t.blink_off()
    t.write_text(2, 0, "blink off")


def demo_ping(t: Terminal):
    """Send DC4 probes with different payloads and report echoes."""
    print("Sending DC4 probes (terminal should echo 0x14 <payload> each):")
    for payload in (0x00, 0x41, 0x55, 0xAA, 0xFF):
        reply = t.dc4_ping(payload, timeout=1.0)
        print(f"  DC4 + 0x{payload:02X} -> {reply.hex(' ') if reply else '(no reply)'}")


def demo_status(t: Terminal):
    """Exercise all three response paths."""
    for label, fn in [
        ("DC3 0xC3 (status report)", t.status_report),
        ("DC3 0x08 (BS / status query)", t.status_query),
        ("DC3 0x09 (TAB / address query)", t.address_query),
    ]:
        reply = fn()
        print(f"  {label:32s} -> {reply.hex(' ') if reply else '(no reply)'}")


def demo_single(t: Terminal):
    """Use the DC1 'display one char at cursor' path."""
    t.clear_screen()
    t.goto(0, 0)
    for ch in "single-char DC1 write":
        t.write_one(ord(ch))
        time.sleep(0.08)


def demo_cycle(t: Terminal):
    """Run every demo with pauses."""
    for name, fn in [
        ("banner", demo_banner),
        ("chargen", demo_chargen),
        ("positions", demo_positions),
        ("umlaut", demo_umlaut),
        ("single", demo_single),
        ("blink", demo_blink),
        ("ping", demo_ping),
        ("status", demo_status),
    ]:
        print(f"--- {name} ---")
        fn(t)
        time.sleep(1.0)


DEMOS = {
    "clear": demo_clear,
    "banner": demo_banner,
    "chargen": demo_chargen,
    "umlaut": demo_umlaut,
    "positions": demo_positions,
    "blink": demo_blink,
    "ping": demo_ping,
    "status": demo_status,
    "single": demo_single,
    "cycle": demo_cycle,
}


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("port", help="Serial port, e.g. /dev/ttyUSB0 or COM3")
    ap.add_argument("--baud", type=int, default=9600)
    ap.add_argument("--demo", default="cycle",
                    choices=sorted(DEMOS), help="which demo to run")
    args = ap.parse_args()

    t = Terminal(args.port, baud=args.baud)
    try:
        DEMOS[args.demo](t)
    finally:
        t.close()


if __name__ == "__main__":
    main()
