#!/usr/bin/env python3
"""Exercise the Siemens 9772 terminal over its upstream serial port.

Line format (set by the factory firmware):
    19200 baud, 8 data bits, odd parity, 1 stop bit (8O1)

Protocol summary (extracted from firmware disassembly):

    Default state (0x0F):
        STX (0x02)    -> enter text mode (state 0x11)
        DC1 (0x11)    -> next byte = one character written at cursor
        DC3 (0x13)    -> next byte = command (DC3 escape)
        DC4 (0x14)    -> next byte = slave poll; terminal echoes 0x14 + byte

    Text mode (state 0x11, entered by STX):
        ETX (0x03)    -> leave text mode, back to default
        DC3 (0x13)    -> next byte = DC3-escape command (then stay in text mode)
        anything else -> written at cursor, cursor advances. Bytes with
                         bit 7 set are forced to 0x7F (DEL) before display.

    DC3-escape commands (following a DC3 either in default or text mode):
        0x08          -> transmit `0x12 0x20` (status response)
        0x09          -> transmit `0x12 <id>` where <id> is the slave address
                          read from DIP switches: 0x01, 0x02 or 0x04
        0x30-0x57     -> set cursor to BCD column 0..39 within current row
        0x80-0x8F     -> set display bank/row (P2 upper nibble = cmd & 0x0F)
        0xC0          -> fill current bank with 0x00
        0xC1          -> fill current bank with 0x20 (space) -- "clear screen"
        0xC2          -> all banks invisible + fill bank 0 with 0x00
        0xC3          -> transmit `0x12 0x80` (status report)
        0xC4          -> clear current row to 0x00, cursor home
        0xC5          -> clear current row to 0x20, cursor home
        0xC6          -> start attribute-blink mode A (toggle P1.0 each tick)
        0xC7          -> start attribute-blink mode B (toggle P1.1 each tick)
        0xC8          -> stop attribute blink (freeze current state)
        anything else -> reset to default state

    DC4 (0x14) slave-response:
        terminal waits for T0 low (TxRDY), then transmits 0x14 followed
        by the received byte back over the same line. Useful for
        ping/address probing on the RS-422/485 bus.

Underline: the firmware provides NO software control of the
per-character underline. P1.0 and P1.1 are the only P1 bits it
manipulates, and those drive attribute blink (cursor / alt-blink). The
global "underline under every cell" is therefore hardware-generated by
the TTL display controller and is always on.

This script assumes a straight two-wire connection via an RS-422/485
transceiver onto the terminal's DTE upstream port.

Usage:
    python3 exercise.py /dev/ttyUSB0 --demo bringup    # first-contact check
    python3 exercise.py /dev/ttyUSB0                   # = --demo cycle
    python3 exercise.py /dev/ttyUSB0 --demo clear
    python3 exercise.py /dev/ttyUSB0 --demo chargen    # show whole charset
    python3 exercise.py /dev/ttyUSB0 --demo umlaut
    python3 exercise.py /dev/ttyUSB0 --demo blink
    python3 exercise.py /dev/ttyUSB0 --demo ping       # DC4 probe

    python3 exercise.py /dev/ttyUSB0 --listen-hello    # reset the terminal
                                                        # before running; prints
                                                        # the 0x12 0x90 greeting
"""
from __future__ import annotations

import argparse
import sys
import time

try:
    import serial
except ImportError:
    sys.exit("pyserial is required: pip install pyserial")


# --- Protocol constants --------------------------------------------------

STX = 0x02
ETX = 0x03
BS  = 0x08
TAB = 0x09
DC1 = 0x11
DC2 = 0x12      # response prefix (terminal -> host)
DC3 = 0x13
DC4 = 0x14

# DC3-escape commands (the byte sent after a DC3)
CMD_STATUS_QUERY    = BS    # 0x08: tx 0x12 0x20
CMD_ADDRESS_QUERY   = TAB   # 0x09: tx 0x12 <slave-id>  (0x01/0x02/0x04)
CMD_FILL_NULL       = 0xC0
CMD_CLEAR_SCREEN    = 0xC1  # fill with space (0x20)
CMD_HIDE_ALL        = 0xC2  # bit-7-clear every cell + fill bank 0 with 0x00
CMD_STATUS_REPORT   = 0xC3  # transmits 0x12 0x80
CMD_CLEAR_ROW_NULL  = 0xC4  # clear current row to 0x00, cursor home
CMD_CLEAR_ROW_SPACE = 0xC5  # clear current row to 0x20, cursor home
CMD_BLINK_A_START   = 0xC6  # P1.0 toggling -> cursor blink
CMD_BLINK_B_START   = 0xC7  # P1.1 toggling -> alt blink
CMD_BLINK_STOP      = 0xC8

# Row / column encoding: cursor position is given by a byte in [0x30 .. 0x57].
# The firmware subtracts 0x30 and looks up page-3 BCD table; the result is a
# value 0..39 that drives R1 (display-cell offset within the current row).
def col_byte(col: int) -> int:
    """Encode column 0..39 as the wire byte expected after DC3."""
    if not 0 <= col <= 39:
        raise ValueError(f"column {col} out of range 0..39")
    return 0x30 + col


def row_byte(row: int) -> int:
    """Encode display row/bank as a 0x80..0x8F byte after DC3.

    The firmware sets P2 upper nibble = (byte & 0x0F), so rows map 1:1 to
    0x80..0x8F. The RAM[0x16] limit (set from DIP switches) caps the row
    count at either 2, 6 or 12 banks. Rows beyond that are rejected.
    """
    if not 0 <= row <= 15:
        raise ValueError(f"row {row} out of range 0..15")
    return 0x80 + row


# --- Serial helpers ------------------------------------------------------

class Terminal:
    def __init__(self, port: str, baud: int = 19200):
        # Some UARTs accept PARITY_ODD directly. 8O1 frame: 8 data + parity + 1 stop.
        self.ser = serial.Serial(
            port=port,
            baudrate=baud,
            bytesize=serial.EIGHTBITS,
            parity=serial.PARITY_ODD,
            stopbits=serial.STOPBITS_ONE,
            timeout=0.5,
        )

    def send(self, *bs):
        """Send a sequence of ints/bytes/strs."""
        buf = bytearray()
        for b in bs:
            if isinstance(b, int):
                buf.append(b & 0xFF)
            elif isinstance(b, (bytes, bytearray)):
                buf.extend(b)
            elif isinstance(b, str):
                buf.extend(b.encode("latin-1"))
            else:
                raise TypeError(f"bad arg {type(b)}")
        self.ser.write(bytes(buf))
        self.ser.flush()

    def read(self, n: int, timeout: float | None = None) -> bytes:
        if timeout is not None:
            self.ser.timeout = timeout
        return self.ser.read(n)

    def close(self):
        self.ser.close()

    # Protocol primitives
    def clear_screen(self):
        """Fill the whole display with spaces."""
        self.send(DC3, CMD_CLEAR_SCREEN)

    def fill_null(self):
        """Fill the whole display with 0x00 (all cells invisible)."""
        self.send(DC3, CMD_FILL_NULL)

    def clear_row_null(self):
        """Clear current row to 0x00 and park cursor at column 0."""
        self.send(DC3, CMD_CLEAR_ROW_NULL)

    def clear_row_space(self):
        """Clear current row to 0x20 and park cursor at column 0."""
        self.send(DC3, CMD_CLEAR_ROW_SPACE)

    def hide_all(self):
        """DC3 0xC2: bit-7-clear every cell on every bank, then fill bank 0
        with 0x00. Effectively 'blank the screen but don't touch the data'
        on the banks that were already there."""
        self.send(DC3, CMD_HIDE_ALL)

    def goto(self, row: int, col: int):
        """Move cursor to (row, col) via DC3 escapes. Row 0 = top,
        col 0 = left. Safe to call outside a text block."""
        self.send(DC3, row_byte(row), DC3, col_byte(col))

    def home(self):
        """Move cursor to (0, 0) - the same place the boot sequence leaves it."""
        self.goto(0, 0)

    def write_text(self, row: int | None, col: int | None, s: str):
        """Write a string at (row, col). Uses STX ... ETX framing and
        DC3-positioning inside the block. Row/col may be None to skip."""
        self.send(STX)
        if row is not None:
            self.send(DC3, row_byte(row))
        if col is not None:
            self.send(DC3, col_byte(col))
        self.send(s)  # literal bytes; bit 7 is filtered by firmware
        self.send(ETX)

    def write_one(self, ch: int):
        """Display one character at the current cursor (DC1 <char>)."""
        self.send(DC1, ch)

    def blink_a(self):      self.send(DC3, CMD_BLINK_A_START)
    def blink_b(self):      self.send(DC3, CMD_BLINK_B_START)
    def blink_off(self):    self.send(DC3, CMD_BLINK_STOP)

    def status_report(self, timeout: float = 1.0) -> bytes:
        """DC3 0xC3 -> expect `0x12 0x80` back."""
        self.ser.reset_input_buffer()
        self.send(DC3, CMD_STATUS_REPORT)
        return self.read(2, timeout=timeout)

    def status_query(self, timeout: float = 1.0) -> bytes:
        """DC3 0x08 (BS) -> expect `0x12 0x20` back."""
        self.ser.reset_input_buffer()
        self.send(DC3, CMD_STATUS_QUERY)
        return self.read(2, timeout=timeout)

    def address_query(self, timeout: float = 1.0) -> bytes:
        """DC3 0x09 (TAB) -> expect `0x12 <slave-id>` back. <slave-id> is
        0x01, 0x02 or 0x04 depending on the DIP switches read at boot."""
        self.ser.reset_input_buffer()
        self.send(DC3, CMD_ADDRESS_QUERY)
        return self.read(2, timeout=timeout)

    def dc4_ping(self, payload: int = 0x00, timeout: float = 1.0) -> bytes:
        """Slave-poll: terminal echoes 0x14 <payload> back to the host."""
        self.ser.reset_input_buffer()
        self.send(DC4, payload)
        return self.read(2, timeout=timeout)

    def read_power_on_hello(self) -> bytes:
        """Block until the terminal's power-on greeting (0x12 0x90)
        arrives, then return it. The firmware emits this pair of bytes
        on every reset, so reset the terminal after calling this."""
        self.ser.timeout = None
        return self.ser.read(2)


# --- Demos ---------------------------------------------------------------

def demo_clear(t: Terminal):
    t.clear_screen()


def demo_bringup(t: Terminal):
    """Minimal 'is the wiring right?' check.

    Sends DC3 0xC1 to clear the screen to spaces (replacing the boot-time
    0x00 dots), positions the cursor at (0, 0), writes a short string,
    then queries the slave address. Use this as your first-ever command
    sequence against a freshly-connected terminal."""
    print("Clearing screen (DC3 0xC1)...")
    t.clear_screen()
    time.sleep(0.3)
    print("Cursor home, writing 'HELLO 9772'...")
    t.write_text(0, 0, "HELLO 9772")
    time.sleep(0.3)
    print("Asking for the slave address (DC3 0x09)...")
    reply = t.address_query()
    if reply:
        print(f"  terminal replied: {reply.hex(' ')}"
              f"   (DIP address = 0x{reply[1]:02X})" if len(reply) >= 2 else "")
    else:
        print("  no reply within 1s -- check TX wiring / parity")


def demo_banner(t: Terminal):
    t.clear_screen()
    time.sleep(0.2)
    t.write_text(0, 0, "SIEMENS 9772 TERMINAL")
    t.write_text(1, 0, "exercise.py running")


def demo_chargen(t: Terminal):
    """Write every printable code from 0x20 to 0x7A across the rows."""
    t.clear_screen()
    time.sleep(0.2)
    # 40 cells per row; put 0x20..0x7A in blocks of 40 starting on row 0.
    codes = list(range(0x20, 0x80))
    for start in range(0, len(codes), 40):
        row = start // 40
        chunk = bytes(codes[start:start + 40])
        t.send(STX, DC3, row_byte(row), DC3, col_byte(0))
        # 0x03 (ETX) and control chars can confuse the text-mode handler,
        # so send them as one-shots via DC1.
        for b in chunk:
            if b in (ETX, DC1, DC3, DC4):
                t.send(DC1, b)
            else:
                t.send(b)
        t.send(ETX)


def demo_umlaut(t: Terminal):
    """Show the chargen's upper-page glyphs.

    Per the firmware/chargen analysis, codes 0x5B-0x5E and 0x7B-0x7E
    are remapped by hardware on the display board to the upper chargen
    page. With the German MODE strap they show:

        0x5B -> Ä   0x5C -> Ö   0x5D -> Ü   0x5E -> ^
        0x7B -> ä   0x7C -> ö   0x7D -> ü   0x7E -> ß

    With the ASCII MODE strap the same codes show the original
    `[ \\ ] ^` / `{ | } ~` glyphs.

    No special escape is needed -- send them as plain ASCII bytes inside
    a normal STX...ETX text block. This demo therefore tells you which
    way the MODE strap is set on your unit by what shows up on screen.
    """
    t.clear_screen()
    time.sleep(0.2)
    # Row 0: the eight test codes
    t.write_text(0, 0, "[\\]^{|}~  <- as wire bytes")
    # Row 1: their German equivalents (for the eyeball test)
    t.write_text(1, 0, "AOU^aou")  # ASCII fallback for the German chars
    t.write_text(2, 0, "If MODE=DE, row 0 shows AeOeUe^aeoeues")
    t.write_text(3, 0, "If MODE=US, row 0 shows the brackets/curly")


def demo_positions(t: Terminal):
    """Walk one character across all 40 columns, twice."""
    t.clear_screen()
    for col in range(40):
        t.write_text(0, col, "*")
        time.sleep(0.05)
    for col in range(40):
        t.write_text(0, col, " ")
        time.sleep(0.05)


def demo_blink(t: Terminal):
    """Enter blink mode A for 3s, mode B for 3s, then stop."""
    t.clear_screen()
    t.write_text(0, 0, "BLINK A (P1.0 toggle)")
    t.blink_a()
    time.sleep(3.0)
    t.write_text(1, 0, "BLINK B (P1.1 toggle)")
    t.blink_b()
    time.sleep(3.0)
    t.blink_off()
    t.write_text(2, 0, "blink off")


def demo_ping(t: Terminal):
    """Send DC4 probes with different payloads and report echoes."""
    print("Sending DC4 probes (terminal should echo 0x14 <payload> each):")
    for payload in (0x00, 0x41, 0x55, 0xAA, 0xFF):
        reply = t.dc4_ping(payload, timeout=1.0)
        print(f"  DC4 + 0x{payload:02X} -> {reply.hex(' ') if reply else '(no reply)'}")


def demo_status(t: Terminal):
    """Exercise all three response paths."""
    for label, fn in [
        ("DC3 0xC3 (status report)", t.status_report),
        ("DC3 0x08 (BS / status query)", t.status_query),
        ("DC3 0x09 (TAB / address query)", t.address_query),
    ]:
        reply = fn()
        print(f"  {label:32s} -> {reply.hex(' ') if reply else '(no reply)'}")


def demo_single(t: Terminal):
    """Use the DC1 'display one char at cursor' path."""
    t.clear_screen()
    t.goto(0, 0)
    for ch in "single-char DC1 write":
        t.write_one(ord(ch))
        time.sleep(0.08)


_CLASSIC_GLYPHS = {
    'A': [' # ', '# #', '###', '# #', '# #'],
    'C': ['###', '#  ', '#  ', '#  ', '###'],
    'G': ['###', '#  ', '# #', '# #', '###'],
    'I': ['###', ' # ', ' # ', ' # ', '###'],
    'L': ['#  ', '#  ', '#  ', '#  ', '###'],
    'M': ['# #', '###', '# #', '# #', '# #'],
    'N': ['# #', '###', '###', '# #', '# #'],
    'O': ['###', '# #', '# #', '# #', '###'],
    'P': ['###', '# #', '###', '#  ', '#  '],
    'S': ['###', '#  ', '###', '  #', '###'],
    'T': ['###', ' # ', ' # ', ' # ', ' # '],
    'U': ['# #', '# #', '# #', '# #', '###'],
}


def _render_block_word(word: str, screen_cols: int = 40) -> list[str]:
    """Render WORD as a 5-row, 3-column-per-letter block-font banner,
    centered in SCREEN_COLS columns. Letters are separated by one space."""
    rows = ['' for _ in range(5)]
    for i, ch in enumerate(word):
        glyph = _CLASSIC_GLYPHS[ch]
        for r in range(5):
            if i:
                rows[r] += ' '
            rows[r] += glyph[r]
    pad = max(0, (screen_cols - len(rows[0])) // 2)
    return [(' ' * pad) + row for row in rows]


def demo_classic(t: Terminal):
    """Render a 'CLASSIC COMPUTING' ASCII-art banner using a 3x5 block
    font. Designed for the 12-row (480-cell) display mode: rows 0-4 show
    'CLASSIC', rows 6-10 show 'COMPUTING'. In 6-row mode only the
    'CLASSIC' line and the top of 'COMPUTING' will be visible; in 2-row
    mode you'll only see the top stripe."""
    classic = _render_block_word('CLASSIC')        # 27 cols + 6 pad = 33
    computing = _render_block_word('COMPUTING')    # 35 cols + 2 pad = 37

    t.clear_screen()
    time.sleep(0.3)

    for r, line in enumerate(classic):
        t.write_text(r, 0, line)
    for r, line in enumerate(computing):
        t.write_text(6 + r, 0, line)


def demo_cycle(t: Terminal):
    """Run every demo with pauses."""
    for name, fn in [
        ("banner", demo_banner),
        ("classic", demo_classic),
        ("chargen", demo_chargen),
        ("positions", demo_positions),
        ("umlaut", demo_umlaut),
        ("single", demo_single),
        ("blink", demo_blink),
        ("ping", demo_ping),
        ("status", demo_status),
    ]:
        print(f"--- {name} ---")
        fn(t)
        time.sleep(1.0)


DEMOS = {
    "clear": demo_clear,
    "bringup": demo_bringup,
    "banner": demo_banner,
    "classic": demo_classic,
    "chargen": demo_chargen,
    "umlaut": demo_umlaut,
    "positions": demo_positions,
    "blink": demo_blink,
    "ping": demo_ping,
    "status": demo_status,
    "single": demo_single,
    "cycle": demo_cycle,
}


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("port", help="Serial port, e.g. /dev/ttyUSB0 or COM3")
    ap.add_argument("--baud", type=int, default=19200)
    ap.add_argument("--demo", default="cycle",
                    choices=sorted(DEMOS), help="which demo to run")
    ap.add_argument("--listen-hello", action="store_true",
                    help="Instead of a demo, block waiting for the "
                         "terminal's power-on greeting (0x12 0x90) and "
                         "print it. Reset the terminal after launching.")
    args = ap.parse_args()

    t = Terminal(args.port, baud=args.baud)
    try:
        if args.listen_hello:
            print("Waiting for power-on greeting (reset the terminal now; Ctrl-C to abort)...")
            reply = t.read_power_on_hello()
            print(f"received: {reply.hex(' ')}")
            if reply == b"\x12\x90":
                print("  -> matches the expected power-on 0x12 0x90 greeting")
            else:
                print("  -> does NOT match 0x12 0x90 - check baud/parity/reset")
        else:
            DEMOS[args.demo](t)
    finally:
        t.close()


if __name__ == "__main__":
    main()
